"""scores table update

Revision ID: 181904f6ad42
Revises: 8e50abe729a0
Create Date: 2019-12-23 20:51:06.370903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181904f6ad42'
down_revision = '8e50abe729a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('gameType', sa.String(length=64), nullable=True))
    op.drop_index('ix_score_score', table_name='score')
    op.drop_index('ix_score_username', table_name='score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_score_username', 'score', ['username'], unique=1)
    op.create_index('ix_score_score', 'score', ['score'], unique=1)
    op.drop_column('score', 'gameType')
    # ### end Alembic commands ###
